package com.augustoomb.api_loja_do_sol_ecommerce.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.math.BigDecimal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import com.augustoomb.api_loja_do_sol_ecommerce.dto.ProductRequestDTO;
import com.augustoomb.api_loja_do_sol_ecommerce.dto.ProductResponseDTO;
import com.augustoomb.api_loja_do_sol_ecommerce.dto.StockAdjustmentRequestDTO;
import com.augustoomb.api_loja_do_sol_ecommerce.dto.StockMovementRequestDTO;
import com.augustoomb.api_loja_do_sol_ecommerce.exception.BusinessException;
import com.augustoomb.api_loja_do_sol_ecommerce.model.Category;
import com.augustoomb.api_loja_do_sol_ecommerce.model.MovementType;
import com.augustoomb.api_loja_do_sol_ecommerce.repository.CategoryRepository;

@SpringBootTest
@Transactional
class StockIntegrationTest {

    @Autowired
    private ProductService productService;
    @Autowired
    private StockService stockService;
    @Autowired
    private CategoryRepository categoryRepository;

    private Category category;

    @BeforeEach
    void setUp() {
        category = categoryRepository.findAll().stream().findFirst()
                .orElseGet(() -> categoryRepository.save(new Category("Categoria Teste", "criada em teste")));
    }

    @Test
    void stockFlowUpdatesBalanceAndRecordsMovements() {
        ProductResponseDTO product = createProduct("SKU-FLOW", 0, 2);

        StockMovementRequestDTO entry = new StockMovementRequestDTO();
        entry.setQuantity(10);
        entry.setReason("Compra inicial");
        stockService.recordEntry(product.getId(), entry, null);

        StockMovementRequestDTO out = new StockMovementRequestDTO();
        out.setQuantity(4);
        out.setReason("Venda");
        stockService.recordWithdrawal(product.getId(), out, null);

        StockAdjustmentRequestDTO adjust = new StockAdjustmentRequestDTO();
        adjust.setNewStock(5);
        adjust.setReason("Inventário");
        stockService.recordAdjustment(product.getId(), adjust, null);

        assertEquals(5, productService.findById(product.getId()).getStock());
        assertEquals(3, stockService.findMovementsByProduct(product.getId()).size());
        assertEquals(1, stockService.findMovements(product.getId(), MovementType.ENTRADA, null, null).size());
        assertEquals(1, stockService.findMovements(product.getId(), MovementType.SAIDA, null, null).size());
        assertEquals(1, stockService.findMovements(product.getId(), MovementType.AJUSTE, null, null).size());
    }

    @Test
    void withdrawalBeyondBalanceIsRejectedAndBalanceIsKept() {
        ProductResponseDTO product = createProduct("SKU-REJECT", 2, 0);

        StockMovementRequestDTO out = new StockMovementRequestDTO();
        out.setQuantity(5);
        out.setReason("Venda");

        assertThrows(BusinessException.class, () -> stockService.recordWithdrawal(product.getId(), out, null));

        assertEquals(2, productService.findById(product.getId()).getStock());
        assertEquals(0, stockService.findMovementsByProduct(product.getId()).size());
    }

    @Test
    void duplicateSkuIsRejected() {
        ProductRequestDTO first = new ProductRequestDTO();
        first.setName("Produto A");
        first.setSku("SKU-DUPLICADO");
        first.setPrice(new BigDecimal("10.00"));
        first.setStock(0);
        first.setMinimumStock(0);
        first.setEnabled(true);
        first.setCategoryId(category.getId());
        productService.create(first);

        ProductRequestDTO second = new ProductRequestDTO();
        second.setName("Produto B");
        second.setSku("sku-duplicado");
        second.setPrice(new BigDecimal("20.00"));
        second.setStock(0);
        second.setMinimumStock(0);
        second.setEnabled(true);
        second.setCategoryId(category.getId());

        assertThrows(BusinessException.class, () -> productService.create(second));
    }

    @Test
    void blankSkuIsAutoGenerated() {
        ProductRequestDTO dto = new ProductRequestDTO();
        dto.setName("Cabo HDMI");
        dto.setPrice(new BigDecimal("25.00"));
        dto.setStock(0);
        dto.setMinimumStock(1);
        dto.setEnabled(true);
        dto.setCategoryId(category.getId());

        ProductResponseDTO created = productService.create(dto);

        org.junit.jupiter.api.Assertions.assertTrue(created.getSku().startsWith("CABO-HDMI-"));
    }

    private ProductResponseDTO createProduct(String sku, int stock, int minimumStock) {
        ProductRequestDTO dto = new ProductRequestDTO();
        dto.setName("Produto " + sku);
        dto.setSku(sku);
        dto.setPrice(new BigDecimal("10.00"));
        dto.setStock(stock);
        dto.setMinimumStock(minimumStock);
        dto.setEnabled(true);
        dto.setCategoryId(category.getId());
        return productService.create(dto);
    }
}
